ALTER TABLE saas_plans ADD COLUMN IF NOT EXISTS module_whatsapp BOOLEAN DEFAULT FALSE;
ALTER TABLE saas_plans ADD COLUMN IF NOT EXISTS module_multi_depot BOOLEAN DEFAULT FALSE;
ALTER TABLE saas_plans ADD COLUMN IF NOT EXISTS module_livreurs BOOLEAN DEFAULT FALSE;
ALTER TABLE saas_plans ADD COLUMN IF NOT EXISTS module_rapport_avance BOOLEAN DEFAULT FALSE;
ALTER TABLE saas_plans ADD COLUMN IF NOT EXISTS module_white_label BOOLEAN DEFAULT FALSE;
ALTER TABLE saas_plans ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE saas_plans ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
DROP POLICY IF EXISTS "SuperAdmins_manage_plans" ON saas_plans;
DROP POLICY IF EXISTS "Public_read_plans" ON saas_plans;
CREATE POLICY "Public_read_plans" ON saas_plans FOR SELECT USING (true);
CREATE POLICY "SuperAdmins_manage_plans" ON saas_plans FOR ALL TO authenticated USING (public.is_superadmin()) WITH CHECK (public.is_superadmin());
CREATE OR REPLACE FUNCTION update_saas_plan(p_id TEXT, p_name TEXT, p_price_fcfa BIGINT, p_description TEXT, p_is_popular BOOLEAN, p_module_caisse BOOLEAN, p_module_audit BOOLEAN, p_module_api BOOLEAN, p_module_whatsapp BOOLEAN DEFAULT FALSE, p_module_multi_depot BOOLEAN DEFAULT FALSE, p_module_livreurs BOOLEAN DEFAULT FALSE, p_module_rapport_avance BOOLEAN DEFAULT FALSE, p_module_white_label BOOLEAN DEFAULT FALSE) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE v_rows INT; BEGIN IF NOT public.is_superadmin() THEN RETURN jsonb_build_object('success', false, 'error', 'Acces refuse'); END IF; UPDATE saas_plans SET name=p_name, price_fcfa=p_price_fcfa, description=p_description, is_popular=p_is_popular, module_caisse=p_module_caisse, module_audit=p_module_audit, module_api=p_module_api, module_whatsapp=COALESCE(p_module_whatsapp,FALSE), module_multi_depot=COALESCE(p_module_multi_depot,FALSE), module_livreurs=COALESCE(p_module_livreurs,FALSE), module_rapport_avance=COALESCE(p_module_rapport_avance,FALSE), module_white_label=COALESCE(p_module_white_label,FALSE), updated_at=now() WHERE id=p_id; GET DIAGNOSTICS v_rows = ROW_COUNT; IF v_rows = 0 THEN RETURN jsonb_build_object('success', false, 'error', 'Plan non trouve: ' || p_id); END IF; RETURN jsonb_build_object('success', true, 'rows_updated', v_rows); END; $$;
